BEGIN TRANSACTION;
-- MODULO ---------------------------------> FERIAS
-- CLIENTES FERIAS
CREATE TABLE PROFFLINE_TB_FERIAS_CLIENTE
(codigoCliente TEXT,
nombreCliente TEXT,
razonSocial TEXT,
RUC TEXT,
telefono TEXT,
celular TEXT,
otroTelefono TEXT,
ciudad TEXT,
correo TEXT);

-- ASISTENCIA FERIAS
CREATE TABLE PROFFLINE_TB_FERIAS_ASISTENCIA
(codigoCliente TEXT,
razonSocial text,
RELACION TEXT,
ciudadCliente text,
INVITADO TEXT,
correo text,
FACEBOOK TEXT,
TWITTER TEXT,
telefono text,
celular text,
otroTelefono text,
INTERECESESPECIALES TEXT,
OBSERVACION TEXT,
EJERCICIO TEXT,
SECUENCIA TEXT,
CIUDADFERIA TEXT,
IDUSUARIO TEXT,
HORAASISTENCIA TEXT,
FECHAASISTENCIA TEXT,
SOURCE TEXT,
ID INTEGER PRIMARY KEY,
sincronizacion TEXT,
GREMIOINST TEXT,
PROFESION TEXT);

-- LUGARES FERIAS
CREATE TABLE PROFFLINE_TB_FERIAS_LUGAR
(codigoCiudad TEXT,
nombreCiudad TEXT);

-- RELACIONES FERIAS
CREATE TABLE PROFFLINE_TB_FERIAS_RELACION
(codigoRelacion TEXT,
tipoRelacion TEXT);

-- tvk7t TABLA EN SAP -- -- PROFESIONALES FERIAS
CREATE TABLE PROFFLINE_TB_FERIAS_PROFESION
(CODIGOPROFESION TEXT,
NOMBREPROFESION TEXT);

--tvk8t TABLA EN SAP -- -- GREMIO E INSTITUCION EDUCATIVA FERIAS
CREATE TABLE PROFFLINE_TB_FERIAS_GREMIO_INST
(CODIGOGREMIO TEXT,
NOMBREGREMIO TEXT);

COMMIT;