BEGIN TRANSACTION;
-- ---------------------------------> FASE 1 <---------------------------------
-- MODULO ---------------------------------> ADMINISTRACION
-- USUARIOS
CREATE TABLE PROFFLINE_TB_USUARIO
(txtMandante TEXT,
txtIdUsuario TEXT,
txtNombreUsuario TEXT,
txtClaveUsuario TEXT,
txtFechaRegistroUsuario TEXT,
txtFechaUltimoAccesoUsuario TEXT,
txtHoraUltimoAccesoUsuario TEXT,
numCambioClave NUMERIC,
numIntento NUMERIC,
numUsuarioBloqueado NUMERIC,
txtIdentificacion TEXT,
txtUsuario TEXT,
txtDivision TEXT);
-- ROLES
CREATE TABLE PROFFLINE_TB_ROL
(txtMandante TEXT,
txtIdRol TEXT,
txtNombreRol TEXT);
-- USUARIOS ROLES
CREATE TABLE PROFFLINE_TB_USUARIO_ROL
(txtMandante TEXT,
txtIdUsuario TEXT,
txtIdRoL TEXT);
-- VISTAS
CREATE TABLE PROFFLINE_TB_VISTA
(txtMandante TEXT,
txtNombreVista TEXT,
txtDescVista TEXT);
-- ROLES VISTAS
CREATE TABLE PROFFLINE_TB_VISTA_ROL
(txtMandante TEXT,
txtIdRol TEXT,
txtNombreVista TEXT);
-- DISPOSITIVOS
CREATE TABLE PROFFLINE_TB_DISPOSITIVO
(txtIdDis TEXT,
txtTipDis TEXT,
txtSerie TEXT,
txtCodAct TEXT,
txtSimm TEXT,
txtImei TEXT,
txtNroTelf TEXT,
txtNumSeg TEXT,
txtIdUsu TEXT,
txtUsu TEXT,
txtDisRel TEXT,
numEstado NUMERIC,
txtObs TEXT,
txtUsuReg TEXT,
txtFecReg TEXT,
txtHorReg TEXT,
txtUsuUpd TEXT,
txtFecUpd TEXT,
txtHorUpd TEXT);

-- MODULO ---------------------------------> PLANIFICACION
-- EMPLEADOS
CREATE TABLE PROFFLINE_TB_EMPLEADO 
(txtIdEmpleado TEXT, 
txtNombreEmpleado TEXT, 
txtIdSupervisor TEXT);
-- CLIENTES
CREATE TABLE PROFFLINE_TB_CLIENTE (
txtOficinaVentas TEXT, 
txtGrupoVentas TEXT,
txtIndicadorImpuesto TEXT,
txtIdCliente TEXT,
txtCompaniaCliente TEXT,
txtNombreCliente TEXT,
txtApellidosCliente TEXT,
txtEmailCliente TEXT,
txtTelefonoPrivadoCliente TEXT,
txtTelefonoTrabajoCliente TEXT,
txtTelefonoMovilCliente TEXT,
txtNumeroFaxCliente TEXT,
txtDireccionCliente TEXT,
txtCiudadCliente TEXT,
txtEstadoProvinciaCliente TEXT,
txtCodigoPostalCliente TEXT,
txtDescripcionTipologia TEXT,
txtCodigoTipologia TEXT,
txtLimiteCredito TEXT,
txtClaseRiesgo TEXT,
txtMarcaBloqueoAlmacen TEXT,
txtStrCodTipologia TEXT,
txtStrDescTipologia TEXT,
txtCodOrgVentas TEXT,
txtCodCanalDist TEXT,
txtCodSector TEXT);
-- EMPLEADOS CLIENTES
CREATE TABLE PROFFLINE_TB_EMPLEADO_CLIENTE
(txtIdEmpleado TEXT,
txtIdCliente TEXT);
-- FRECUENCIA
CREATE TABLE PROFFLINE_TB_FRECUENCIA 
(numIdFrecuencia NUMERIC, 
numFrecuencia NUMERIC, 
txtFrecuencia TEXT);
INSERT INTO PROFFLINE_TB_FRECUENCIA VALUES(1,7,'7 días');
INSERT INTO PROFFLINE_TB_FRECUENCIA VALUES(2,14,'14 días');
INSERT INTO PROFFLINE_TB_FRECUENCIA VALUES(3,28,'28 días');
-- HORA
CREATE TABLE PROFFLINE_TB_HORA 
(numIdHora NUMERIC, 
txtHora TEXT);
INSERT INTO PROFFLINE_TB_HORA VALUES(1,'08:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(2,'08:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(3,'09:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(4,'09:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(5,'10:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(6,'10:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(7,'11:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(8,'11:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(9,'12:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(10,'12:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(11,'13:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(12,'13:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(13,'14:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(14,'14:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(15,'15:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(16,'15:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(17,'16:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(18,'16:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(19,'17:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(20,'17:30');
INSERT INTO PROFFLINE_TB_HORA VALUES(21,'18:00');
INSERT INTO PROFFLINE_TB_HORA VALUES(22,'18:30');
-- PLANIFICACIONES
CREATE TABLE PROFFLINE_TB_PLANIFICACION 
(txtIdPlan TEXT, 
txtIdVendedor TEXT, 
txtIdJefe TEXT, 
txtIdCliente TEXT, 
txtFechaInicio TEXT, 
txtFechaFin TEXT, 
txtHora TEXT, 
txtNombreCliente TEXT, 
numIdFrecuencia NUMERIC, 
txtMandante TEXT);
-- VISITAS
CREATE TABLE PROFFLINE_TB_VISITA
 (txtIdVendedor TEXT, 
txtIdCliente TEXT, 
txtIdJefe TEXT, 
txtFechaVisita TEXT, 
txtHoraPlaneada TEXT, 
txtHora TEXT, 
txtStatus TEXT, 
txtTipo TEXT, 
txtComentario1 TEXT, 
txtComentario2 TEXT, 
txtDocumentoReferencia TEXT, 
txtVisitaEfectuada TEXT, 
txtIdPlanificacion TEXT, 
txtMandante TEXT);
-- FERIADOS
CREATE TABLE PROFFLINE_TB_FERIADO
(txtSigFeriado TEXT,
txtMesFeriado TEXT,
txtDiaFeriado TEXT,
txtOriFeriado TEXT);
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','08','10','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','10','09','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','11','02','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','11','03','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','05','01','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','05','24','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','12','25','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','01','01','EC');
INSERT INTO PROFFLINE_TB_FERIADO VALUES('F','07','25','EC');

-- MODULO ---------------------------------> PEDIDOS
-- AGENDA
CREATE TABLE PROFFLINE_TB_AGENDA
(txtVendor_Id TEXT, 
txtVendor_Name TEXT, 
txtBegda TEXT, 
txtEndda TEXT, 
txtHora TEXT, 
txtCust_Id TEXT, 
txtCust_Name TEXT, 
txtCust_Addres TEXT, 
txtCust_Telf TEXT, 
txtCust_Telfx TEXT, 
txtCust_1 TEXT, 
txtCu_1 TEXT, 
txtCu_2 TEXT, 
txtCust_Klimk TEXT, 
txtCus TEXT,
txtCust_Available TEXT,
txtDescription TEXT,
txtSt TEXT,  
txtStat TEXT,    
txtTy TEXT,     
txtCust_2 TEXT,          
txtType_Description TEXT,
txtStdRegAge TEXT);
-- CONDICION COMERCIAL ZD01
CREATE TABLE PROFFLINE_TB_CONDICION_1 (Porcentaje TEXT, Tipo TEXT, PrioridadGrupo NUMERIC, PrioridadCondicion NUMERIC, ClaseMaterial TEXT, CondicionPago TEXT, Cliente TEXT);
-- CONDICION COMERCIAL ZD02
CREATE TABLE PROFFLINE_TB_CONDICION_2 (Porcentaje TEXT, Tipo TEXT, PrioridadGrupo NUMERIC, PrioridadCondicion NUMERIC, Canal TEXT, GrupoCliente TEXT, Cliente TEXT);
-- CONDICION_EXPEDICION
CREATE TABLE PROFFLINE_TB_CONDICION_EXPEDICION (txtSincronizado NUMERIC, txtIdCondicion TEXT, txtDescripcion TEXT);
INSERT INTO PROFFLINE_TB_CONDICION_EXPEDICION VALUES(NULL,'01','ESTANDAR');
INSERT INTO PROFFLINE_TB_CONDICION_EXPEDICION VALUES(NULL,'02','TRASLADOS');
INSERT INTO PROFFLINE_TB_CONDICION_EXPEDICION VALUES(NULL,'03','EXPRESS');
INSERT INTO PROFFLINE_TB_CONDICION_EXPEDICION VALUES(NULL,'04','RETIRA PERSONAL');
INSERT INTO PROFFLINE_TB_CONDICION_EXPEDICION VALUES(NULL,'05','SIN TRANSPORTE');
-- JERARQUIA
CREATE TABLE PROFFLINE_TB_JERARQUIA (txtSincronizado NUMERIC, txtIdPadre TEXT, txtPRODH TEXT, txtS TEXT, txtVTEXT TEXT, txtZZSEQ TEXT, txtICON TEXT, txtI TEXT, txtCELLDESIGN TEXT);
-- MATERIAL
CREATE TABLE PROFFLINE_TB_MATERIAL (MATNR TEXT,STOCK TEXT,	S_U TEXT,SHORT_TEXT TEXT,TEXT_LINE TEXT,TARGET_QTY TEXT,PRICE_1 TEXT,PRICE_2 TEXT,PRICE_3 TEXT,PRICE_4 TEXT,PRDHA TEXT,HER TEXT,NORMT TEXT,ZZORDCO TEXT,CELL_DESIGN TEXT,MTART TEXT,TYPEMAT TEXT,GRUPO_COMPRA TEXT,ST_1 TEXT,VENTAS_ACUMULADO NUMERIC,VENTAS_PROMEDIO NUMERIC,CLIENTE TEXT);
-- MATERIAL_STOCK
CREATE TABLE PROFFLINE_TB_MATERIAL_STOCK (MATNR TEXT,STOCK TEXT);
-- MATERIAL_TOP_CLIENTE
CREATE TABLE PROFFLINE_TB_MATERIAL_TOP_CLIENTE (MATNR TEXT,STOCK TEXT,	S_U TEXT,SHORT_TEXT TEXT,TEXT_LINE TEXT,TARGET_QTY TEXT,PRICE_1 TEXT,PRICE_2 TEXT,PRICE_3 TEXT,PRICE_4 TEXT,PRDHA TEXT,HER TEXT,NORMT TEXT,ZZORDCO TEXT,CELL_DESIGN TEXT,MTART TEXT,TYPEMAT TEXT,GRUPO_COMPRA TEXT,ST_1 TEXT,VENTAS_ACUMULADO NUMERIC,VENTAS_PROMEDIO NUMERIC,CLIENTE TEXT);
-- MATERIAL_TOP_TIPOLOGIA
CREATE TABLE PROFFLINE_TB_MATERIAL_TOP_TIPOLOGIA (MATNR TEXT,STOCK TEXT,	S_U TEXT,SHORT_TEXT TEXT,TEXT_LINE TEXT,TARGET_QTY TEXT,PRICE_1 TEXT,PRICE_2 TEXT,PRICE_3 TEXT,PRICE_4 TEXT,PRDHA TEXT,HER TEXT,NORMT TEXT,ZZORDCO TEXT,CELL_DESIGN TEXT,MTART TEXT,TYPEMAT TEXT,GRUPO_COMPRA TEXT,ST_1 TEXT,VENTAS_ACUMULADO NUMERIC,VENTAS_PROMEDIO NUMERIC,CLIENTE TEXT);
-- MATERIAL PROMO OFERTA
CREATE TABLE PROFFLINE_TB_MATERIAL_PROMO_OFERTA (MATNR TEXT,STOCK TEXT,	S_U TEXT,SHORT_TEXT TEXT,TEXT_LINE TEXT,TARGET_QTY TEXT,PRICE_1 TEXT,PRICE_2 TEXT,PRICE_3 TEXT,PRICE_4 TEXT,PRDHA TEXT,HER TEXT,NORMT TEXT,ZZORDCO TEXT,CELL_DESIGN TEXT,MTART TEXT,TYPEMAT TEXT,GRUPO_COMPRA TEXT,ST_1 TEXT,VENTAS_ACUMULADO NUMERIC,VENTAS_PROMEDIO NUMERIC,CLIENTE TEXT);
-- MATERIAL DESCUENTO POLITICA
CREATE TABLE PROFFLINE_TB_MATERIAL_DSCTO_POLITICA (MATNR TEXT,STOCK TEXT,	S_U TEXT,SHORT_TEXT TEXT,TEXT_LINE TEXT,TARGET_QTY TEXT,PRICE_1 TEXT,PRICE_2 TEXT,PRICE_3 TEXT,PRICE_4 TEXT,PRDHA TEXT,HER TEXT,NORMT TEXT,ZZORDCO TEXT,CELL_DESIGN TEXT,MTART TEXT,TYPEMAT TEXT,GRUPO_COMPRA TEXT,ST_1 TEXT,VENTAS_ACUMULADO NUMERIC,VENTAS_PROMEDIO NUMERIC,CLIENTE TEXT);
-- MATERIAL DESCUENTO MANUAL
CREATE TABLE PROFFLINE_TB_MATERIAL_DSCTO_MANUAL (MATNR TEXT,STOCK TEXT,	S_U TEXT,SHORT_TEXT TEXT,TEXT_LINE TEXT,TARGET_QTY TEXT,PRICE_1 TEXT,PRICE_2 TEXT,PRICE_3 TEXT,PRICE_4 TEXT,PRDHA TEXT,HER TEXT,NORMT TEXT,ZZORDCO TEXT,CELL_DESIGN TEXT,MTART TEXT,TYPEMAT TEXT,GRUPO_COMPRA TEXT,ST_1 TEXT,VENTAS_ACUMULADO NUMERIC,VENTAS_PROMEDIO NUMERIC,CLIENTE TEXT);
-- TIPOLOGIA
CREATE TABLE PROFFLINE_TB_TIPOLOGIA (txtSincronizado NUMERIC, MTAR TEXT, MTBEZ TEXT);
-- BLOQUEO ENTREGA
CREATE TABLE PROFFLINE_TB_BLOQUEO_ENTREGA (txtCodigo TEXT, txtDescripcion TEXT);
-- CONDICIÓN PAGO
CREATE TABLE PROFFLINE_TB_CONDICIONES_PAGO (txtZTERM TEXT, txtVTEXT TEXT);
-- CONDICION PAGO DETALLE
CREATE TABLE PROFFLINE_TB_CONDICIONES_PAGO_DETALLE (txtZTERMH TEXT, txtZTERMD TEXT);
-- DETALE DE PEDIDO
CREATE TABLE PROFFLINE_TB_PEDIDO_DETALLE (tipo NUMERIC, id_header NUMERIC, id INTEGER PRIMARY KEY, txtSincronizado NUMERIC, txtPosicion TEXT, txtMaterial TEXT, txtCantidad TEXT, txtCantidadConfirmada TEXT, txtUM TEXT, txtPorcentajeDescuento TEXT, txtDenominacion TEXT, txtPrecioNeto TEXT, txtValorNeto TEXT);
-- CABECERA DE PEDIDO
CREATE TABLE PROFFLINE_TB_PEDIDO_HEADER (txtDisponible TEXT, txtLimiteCredito TEXT, txtClaseRiesgo TEXT, NOMBRE_CLIENTE TEXT, COD_CLIENTE TEXT, VALOR_NETO TEXT, txtVendedor TEXT, txtSincronizado NUMERIC, SHIP_TYPE TEXT, SHIP_COND TEXT, CREATED_BY TEXT, CURRENCY TEXT, SERV_DATE TEXT, BILL_DATE TEXT, DOC_DATE TEXT, SD_DOC_CAT TEXT, PURCH_NO_C TEXT, PRICE_DATE TEXT, DLV_BLOCK TEXT, PMNTTRMS TEXT, PURCH_DATE TEXT, REQ_DATE_H TEXT, SALES_OFF TEXT, SALES_GRP TEXT, DIVISION TEXT, DISTR_CHAN TEXT, SALES_ORG TEXT, DOC_TYPE TEXT, id INTEGER PRIMARY KEY);
-- PARTNERS DE PEDIDO
CREATE TABLE PROFFLINE_TB_PEDIDO_PARTNERS (txtValue TEXT, txtKey TEXT, id INTEGER PRIMARY KEY, txtSincronizado NUMERIC, id_header NUMERIC);
-- COMBOS
CREATE TABLE PROFFLINE_TB_COMBO (unidad TEXT, idCombo INTEGER PRIMARY KEY, codigo TEXT, nombre TEXT, precio TEXT);
-- DETALLE DE COMBOS
CREATE TABLE PROFFLINE_TB_DETALLE_COMBO (cantidad TEXT, idDetalleCombo INTEGER PRIMARY KEY, codigo TEXT, nombre TEXT, precio TEXT, idCombo TEXT);
-- PRUEBA 
CREATE TABLE PROFFLINE_TB_PRUEBA
(txtPruebaAcceso TEXT);
INSERT INTO PROFFLINE_TB_PRUEBA VALUES ('1');
-- SEDE
CREATE TABLE PROFFLINE_TB_SEDE
(txtIdCliente TEXT,
 txtCodigo TEXT,
 txtDireccion TEXT);	
-- CLASE MATERIAL
CREATE TABLE PROFFLINE_TB_CLASE_MATERIAL
(txtCodigoClase TEXT,
txtDescripcionClase TEXT,
txtCodigoMaterial);
-- SUPERVISOR
CREATE TABLE PROFFLINE_TB_SUPERVISOR 
(txtId INTEGER PRIMARY KEY, 
txtIdVendedor TEXT, 
txtIdSupervisor TEXT);
-- ---------------------------------> FASE 1 <---------------------------------

-- ---------------------------------> FASE 2 <---------------------------------
-- MODULO ---------------------------------> DEVOLUCIONES
-- MOTIVO DEVOLUCION
CREATE TABLE PROFFLINE_TB_MOTIVO_DEVOLUCION
(txtMandante TEXT,
txtIdioma TEXT,
txtCodMotDev TEXT,
txtMotDev TEXT);
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','C1','EXHIBICION DE MERCADERIAS');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','C2','LANZAMIENTO Y/O EVENTO');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','C3','DEMOSTRACION');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','D10','EQUIVOCACION CLIENTE SOLICITA MERCADERIA');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV1','Equiv. Toma Pedido x Vend. Sup. Clte');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV2','Equiv. Toma Pedido x CAC');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV3','Equiv. Toma Pedido en Digit. Despacho');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV4','Mercad. Mal estado x Falla Fabric C/Gtia');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV5','Liquidacion de Negocio');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV6','Pagar Planillas');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV7','Cambio de Documento');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV8','ERROR EN DESPACHO');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','DV9','FALTANTES DE MERCADERIA');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','NC1','REPARACIONES CON GARANTIA');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','ND1','DIFERENCIA DE PRECIO');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','ND2','POR INTERES EN MORA');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','ND3','ERROR EN APLICACI�N DE DESCUENTO');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','ND4','COMISION BANCARIA POR CHEQUE PROTES');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','ND5','POR TRANSPORTE DE MERCADERIA');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','ND6','POR GESTION DE COBRANZA');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','R1','REPOSICION DE MERCADERIAS');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','V1','PROMOCIONES');
INSERT INTO PROFFLINE_TB_MOTIVO_DEVOLUCION VALUES('110','ES','V2','CLIENTE SIN STOCK');
-- ---------------------------------> FASE 2 <---------------------------------

-- MODULO ---------------------------------> SINCRONIZACION
-- CABECERA
CREATE TABLE PROFFLINE_TB_SINCRONIZACION
(numIdeSinc NUMERIC,
txtInfSinc TEXT,
numCantReg NUMERIC,
txtFecHor TEXT,
numTie TEXT);
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(1,'Usuarios',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(2,'Roles',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(3,'Agenda',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(4,'Bloqueo de entrega',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(5,'Clase de material',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(6,'Cliente',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(7,'Combos',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(8,'Condiciones comerciales',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(9,'Condiciones de pago',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(10,'Destinatarios',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(11,'Dispositivos',0,'01-01-1900 00:00:00 AM','00:00');
--INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(12,'Empleados',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(13,'Feriados',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(14,'Jerarquía de materiales',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(15,'Lista de materiales',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(16,'Stock de materiales',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(17,'Tipologías',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(18,'Consulta dinámica',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(19,'Banco cliente',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(20,'Hoja maestra crédito',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(21,'Partida individual',0,'01-01-1900 00:00:00 AM','00:00');
--INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(22,'Pedido pendiente devolución',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(23,'Formas de pago de cobranzas',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(24,'Formas de pago de anticipos',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(25,'Bancos Promesa',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(26,'Cobranzas fuera de línea',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(27,'Secuencial Vendedor',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(28,'Parametros Bloqueo',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(29,'Cobranzas Off Line',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(30,'Anticipos Off Line',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(31,'Presupuestos Clientes',0,'01-01-1900 00:00:00 AM','00:00');
INSERT INTO PROFFLINE_TB_SINCRONIZACION VALUES(32,'Marca Estrategica e Indicador',0,'01-01-1900 00:00:00 AM','00:00');

-- DETALLE
CREATE TABLE PROFFLINE_TB_DETALLE_SINCRONIZACION
(txtHorIni TEXT,
numFec NUMERIC,
numIdeSinc NUMERIC,
Eliminado NUMERIC);
--public static final String OPCIONES_PEDIDOS = "8,10,11,12,13,14,15,16,17,19,20,21,22,23,24";
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,1,0);--Usuarios
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:01 AM',24,2,0);--Roles
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:03 AM',24,3,0);--Usuarios Roles
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:04 AM',24,4,0);--Vistas
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:06 AM',24,5,0);--Roles Vistas
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,6,0);--Dispositivos
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,7,0);--Planificacion
--INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:05 AM',6,8,0);--Emp Cle
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,9,0);--Feriados
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,10,0);--Cond Exped
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:02 AM',24,11,0);--Agenda
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,12,0);--Jerarquia
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:03:00 AM',24,13,0);--Material
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,14,0);--Tipologia
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,15,0);--Bloqueo Entrega
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,16,0);--Cond Pago
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:07 AM',24,17,0);--Cliente
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,18,0);--Pedidos
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:20 AM',24,19,0);--Destinatarios
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:01:00 AM',24,20,0);--Combos
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,21,0);--Cond. Comerciales
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:00:00 AM',24,22,0);--Clase Material
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:10:00 AM',24,23,0);--Consulta Dinamica
INSERT INTO PROFFLINE_TB_DETALLE_SINCRONIZACION VALUES('12:12:00 AM',24,24,0);--Stock
-- HISTORIAL
CREATE TABLE PROFFLINE_TB_HISTORIAL_SINCRONIZACION
(numIdeHistSinc NUMERIC,
numIdeSinc NUMERIC,
numCantReg NUMERIC,
txtFecHor TEXT,
numTie NUMERIC);
-- COBRANZAS
CREATE TABLE PROFFLINE_TB_CABECERA_HOJA_MAESTRA_CREDITO
(codigoCliente TEXT,
codigoVendedor TEXT,
nombreCompletoCliente TEXT,
limiteCredito TEXT,
claseRiesgo TEXT,
cupoDisponible TEXT,
valorVencido TEXT,
fuds TEXT,
notaCredito TEXT,
protestante TEXT,
bloqueoCredito TEXT);

CREATE TABLE PROFFLINE_TB_DIA_DEMORA_TRAS_VENCIMIENTO
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
sociedad TEXT,
moneda TEXT,
cuadro TEXT,
partidasVencidas TEXT,
noVencidas TEXT);

CREATE TABLE PROFFLINE_TB_PARTIDA_INDIVIDUAL
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
numeroDocumento TEXT,
claseDocumento TEXT,
posicion TEXT,
fechaDocumento TEXT,
fechaVencimiento TEXT,
registradoEl TEXT,
moneda TEXT,
impteDePos TEXT,
referencia TEXT);

CREATE TABLE PROFFLINE_TB_NOTA_CREDITO
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
numeroDocumento TEXT,
fechaContable TEXT,
fechaDocumento TEXT,
registradoEl TEXT,
moneda TEXT,
importe TEXT,
unOrgRefer TEXT);

CREATE TABLE PROFFLINE_TB_PEDIDO_PENDIENTE_DEVOLUCION
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
numeroDocumento TEXT,
fechaDocumento TEXT,
creadoEl TEXT,
valorNeto TEXT,
nombreVendedor TEXT);

CREATE TABLE PROFFLINE_TB_PROTESTO
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
numeroDocumento TEXT,
fechaContable TEXT,
fechaDocumento TEXT,
registradoEl TEXT,
moneda TEXT,
importe TEXT,
unOrgRefer TEXT);

CREATE TABLE PROFFLINE_TB_VALOR_POR_VENCER
(codigoCliente TEXT,
codigoVendedor TEXT,
mesAnio TEXT,
cantidad TEXT);

CREATE TABLE PROFFLINE_TB_HISTORIAL_PAGO
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
moneda TEXT,
ejercicio TEXT,
periodo TEXT,
conDPP TEXT,
diasDemora1 TEXT,
sinDescuento TEXT,
diasDemora2 TEXT,
ctd TEXT);

CREATE TABLE PROFFLINE_TB_ANTICIPO_CLIENTE
(id INTEGER PRIMARY KEY,
codigoCliente TEXT,
codigoVendedor TEXT,
idFormaPago TEXT,
referencia TEXT,
importe TEXT,
nroCtaBcoCliente TEXT,
idBancoCliente TEXT,
idBancoPromesa TEXT,
observaciones TEXT,
fechaCreacion TEXT,
sincronizado TEXT);

CREATE TABLE PROFFLINE_TB_BANCO_CLIENTE
(codigoCliente TEXT,
nroCtaBcoCliente TEXT,
idBancoCliente TEXT,
descripcionBancoCliente TEXT);

CREATE TABLE PROFFLINE_TB_FORMA_PAGO_ANTICIPO
(idFormaPago TEXT,
descripcionFormaPago TEXT);

CREATE TABLE PROFFLINE_TB_FORMA_PAGO_COBRANZA
(idFormaPago TEXT,
descripcionFormaPago TEXT);

CREATE TABLE PROFFLINE_TB_BANCO_PROMESA
(idBancoPromesa TEXT,
descripcionBancoPromesa TEXT,
tipoRecaudo TEXT);

CREATE TABLE PROFFLINE_TB_PARTIDA_INDIVIDUAL_ABIERTA
(idPartidaIndividualAbierta INTEGER PRIMARY KEY,
codigoCliente TEXT,
docNo TEXT,
pstngDate TEXT,
docDate TEXT,
entryDate TEXT,
expirationDate TEXT,
currency TEXT,
amtDoccur TEXT,
refOrgUn TEXT,
refDocNo TEXT,
docType TEXT,
itemNum TEXT,
postKey TEXT,
psprt TEXT,
pszah TEXT,
psskt TEXT,
invRef TEXT,
invItem TEXT,
isLeaf TEXT,
isExpanded TEXT,
isReadOnly TEXT,
indice TEXT,
displayColor TEXT,
fiscYear TEXT,
fisPeriod TEXT,
sgtxt TEXT,
isReadOnly2 TEXT,
dbCrInd TEXT,
verzn TEXT);

CREATE TABLE PROFFLINE_TB_DETALLE_PAGO_PARTIDA_INDIVIDUAL_ABIERTA
(idDetallePagoPartidaIndividualAbierta INTEGER PRIMARY KEY,
idPartidaIndividualAbierta INTEGER,
docNo TEXT,
pstngDate TEXT,
docDate TEXT,
entryDate TEXT,
expirationDate TEXT,
currency TEXT,
amtDoccur TEXT,
refOrgUn TEXT,
refDocNo TEXT,
docType TEXT,
itemNum TEXT,
postKey TEXT,
psprt TEXT,
pszah TEXT,
psskt TEXT,
invRef TEXT,
invItem TEXT,
isLeaf TEXT,
isExpanded TEXT,
isReadOnly TEXT,
indice TEXT,
displayColor TEXT,
fiscYear TEXT,
fisPeriod TEXT,
sgtxt TEXT,
isReadOnly2 TEXT,
dbCrInd TEXT,
verzn TEXT);
COMMIT;

CREATE TABLE PROFFLINE_TB_CONDICION_1X (Nivel NUMERIC, ClaseCond TEXT, Acceso NUMERIC, TablaCond TEXT, Prioridad NUMERIC, ClaseMaterial TEXT, CondicionPago TEXT, Cliente TEXT, Unidad TEXT, Importe TEXT, Escala TEXT, NroRegCond TEXT, Num TEXT);
CREATE TABLE PROFFLINE_TB_CONDICION_2X (Nivel NUMERIC, ClaseCond TEXT, Acceso NUMERIC, TablaCond TEXT, Prioridad NUMERIC, Cliente TEXT, GrupoCliente TEXT, Canal TEXT, Unidad TEXT, Importe TEXT, Escala TEXT, NroRegCond TEXT, Num TEXT);
CREATE TABLE PROFFLINE_TB_CONDICION_3X (Nivel NUMERIC, ClaseCond TEXT, Acceso NUMERIC, TablaCond TEXT, Prioridad NUMERIC, Material TEXT, DivisionC NUMERIC, DivisionCom NUMERIC, CatProd TEXT, Familia TEXT, Linea TEXT, Grupo TEXT, Cliente TEXT, ZonaPromesa TEXT, Clase TEXT, GrupoCliente TEXT, Unidad TEXT, Importe TEXT, Escala TEXT, NroRegCond TEXT, Num TEXT);
CREATE TABLE PROFFLINE_TB_CONDICION_4X (Nivel NUMERIC, ClaseCond TEXT, Acceso NUMERIC, TablaCond TEXT, Prioridad NUMERIC, Material TEXT, DivisionC NUMERIC, DivisionCom NUMERIC, CatProd TEXT, Familia TEXT, Linea TEXT, Grupo TEXT, Cliente TEXT, ZonaPromesa TEXT, Clase TEXT, GrupoCliente TEXT, Unidad TEXT, Importe TEXT, Escala TEXT, NroRegCond TEXT, Num TEXT);
CREATE TABLE PROFFLINE_TB_CONDICION_5X (Nivel NUMERIC, ClaseCond TEXT, Acceso NUMERIC, TablaCond TEXT, Prioridad NUMERIC, DivisionCom NUMERIC, CatProd TEXT, Familia TEXT, Cliente TEXT, Unidad TEXT, Importe TEXT, Escala TEXT, NroRegCond TEXT, Num TEXT);
CREATE TABLE PROFFLINE_TB_CONDICION_ESCALAS (ClaseCond TEXT, TipoEscala TEXT, NroRegCond TEXT, NumActCond NUMERIC, NumLinea NUMERIC, CantEscala TEXT, ValorEscala TEXT, Importe TEXT);
---------------------------	Marcelo Moyano ------------------------------------
------------------	Tabla de Secuancia por Vendedor----------------------------
CREATE TABLE PROFFLINE_TB_SECUENCIA(txtIdEmpleado TEXT, txtSecuencia TEXT);
------------------ TABLA DE CONDICION DE 4X ZPR1 ------------------------------
CREATE TABLE PROFFLINE_TB_CONDICION_ZPR1 (Nivel NUMERIC, ClaseCond TEXT, Acceso NUMERIC, TablaCond TEXT, Prioridad NUMERIC, Material TEXT, DivisionC NUMERIC, DivisionCom NUMERIC, CatProd TEXT, Familia TEXT, Linea TEXT, Grupo TEXT, Cliente TEXT, ZonaPromesa TEXT, Clase TEXT, GrupoCliente TEXT, Unidad TEXT, Importe TEXT, Escala TEXT, NroRegCond TEXT, Num TEXT);
-------------------------------------------------------------------------------

----------------- TABLA DE PARAMETRIZACIÓN DE PEDIDOS -------------------------
CREATE TABLE PROFFLINE_TB_ZTCONSTANTE(
TXTMODULO TEXT,
TXTNOMBREPROGRAMA TEXT,
TXTNOMBRECAMPO TEXT,
SECUENCIA INTEGER,
TXTOPCION TEXT,
VALOR_1 TEXT,
VALOR_2 TEXT,
TXTNAME TEXT,
TXTFECHA);
-------------------------------------------------------------------------------

--------------------- TABLA DE PRESUPUESTO ------------------------------------
CREATE TABLE PROFFLINE_TB_PRESUPUESTO(
codigoCliente TEXT,
presupuesto_real TEXT,
presupuesto_anual TEXT,
presupuesto_mensual TEXT,
presupuesto_fecha TEXT,
venta_anual TEXT,
venta_mensual TEXT)
-------------------------------------------------------------------------------





